name: CI

on:
  workflow_dispatch:

jobs:
  dev_deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

  qa_deploy:
    runs-on: ubuntu-latest
    environment: qa
    needs: dev_deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'